spring.application.name=backend_skins

# Configuración dinámica para Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/skins_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_secret}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect